openapi: 3.2.0
info:
  title: Discourse API Documentation Backups API
  x-logo:
    url: https://docs.discourse.org/logo.svg
  version: latest
  description: This page contains the documentation on how to use Discourse through API calls.
  license:
    name: MIT
    url: https://docs.discourse.org/LICENSE.txt
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: discourse.example.com
tags:
- name: Backups
paths:
  /admin/backups.json:
    get:
      summary: List backups
      tags:
      - Backups
      operationId: getBackups
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    filename:
                      type: string
                    size:
                      type: integer
                    last_modified:
                      type: string
                  required:
                  - filename
                  - size
                  - last_modified
    post:
      summary: Create backup
      tags:
      - Backups
      operationId: createBackup
      parameters: []
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  success:
                    type: string
                    example: OK
                required:
                - success
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                with_uploads:
                  type: boolean
              required:
              - with_uploads
  /admin/backups/{filename}:
    put:
      summary: Send download backup email
      tags:
      - Backups
      operationId: sendDownloadBackupEmail
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success response
    get:
      summary: Download backup
      tags:
      - Backups
      operationId: downloadBackup
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      - name: token
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success response
