openapi: 3.2.0
info:
  title: Discourse API Documentation Notifications API
  x-logo:
    url: https://docs.discourse.org/logo.svg
  version: latest
  description: This page contains the documentation on how to use Discourse through API calls.
  license:
    name: MIT
    url: https://docs.discourse.org/LICENSE.txt
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: discourse.example.com
tags:
- name: Notifications
paths:
  /notifications.json:
    get:
      summary: Get the notifications that belong to the current user
      tags:
      - Notifications
      operationId: getNotifications
      responses:
        '200':
          description: notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        notification_type:
                          type: integer
                        read:
                          type: boolean
                        created_at:
                          type: string
                        post_number:
                          type:
                          - integer
                          - 'null'
                        topic_id:
                          type:
                          - integer
                          - 'null'
                        slug:
                          type:
                          - string
                          - 'null'
                        data:
                          type: object
                          properties:
                            badge_id:
                              type: integer
                            badge_name:
                              type: string
                            badge_slug:
                              type: string
                            badge_title:
                              type: boolean
                            username:
                              type: string
                  total_rows_notifications:
                    type: integer
                  seen_notification_id:
                    type: integer
                  load_more_notifications:
                    type: string
  /notifications/mark-read.json:
    put:
      summary: Mark notifications as read
      tags:
      - Notifications
      operationId: markNotificationsAsRead
      parameters: []
      responses:
        '200':
          description: notifications marked read
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: '(optional) Leave off to mark all notifications as

                    read'
